### ISSUE TITLE
ImportError: cannot import name 'data' from 'utils'

### ISSUE THREAD

**Issue by bburns8** [bburns8/portfolio_tracker#1]
@gerardsyd 

for some reason I am having trouble with importing modules from the 'utils' and 'app' folder. I've never had a problem with this before and from what I remember this is how I would do it.

**Comment by bburns8** [comment]
Error Traceback:
(venv) blake@pop-os:~/PycharmProjects/portfolio_tracker-dev$ python3 main.py
Traceback (most recent call last):
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/main.py", line 1, in <module>
    from app import app
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/__init__.py", line 22, in <module>
    from app import routes, models
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/routes.py", line 15, in <module>
    from app.forms import LoginForm, RegistrationForm
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/forms.py", line 5, in <module>
    from app.models import User
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/models.py", line 8, in <module>
    from utils import data
ImportError: cannot import name 'data' from 'utils' (/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/utils/__init__.py)
(venv) blake@pop-os:~/PycharmProjects/portfolio_tracker-dev$

**Comment by bburns8** [comment]
(venv) blake@pop-os:~/PycharmProjects/portfolio_tracker-dev$ python3 main.py
Traceback (most recent call last):
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/main.py", line 1, in <module>
    from app import app
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/__init__.py", line 22, in <module>
    from app import routes, models
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/routes.py", line 15, in <module>
    from app.forms import LoginForm, RegistrationForm
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/forms.py", line 5, in <module>
    from app.models import User
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/models.py", line 8, in <module>
    from utils import data
ImportError: cannot import name 'data' from 'utils' (/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/utils/__init__.py)

**Comment by gerardsyd** [comment]
Hi Blake - try adding a __init__.py file in the folder data. It just needs to be a blank file but it will tell python that the folder is a package and then the import should work. Looks like the issue is only for data from utils, the rest is just where the call came from so hopefully that should fix the problem.

**Comment by bburns8** [comment]
that seemed to fix it even though the imports are still highlighted red, must be a bug in PyCharm. however when i run the program now it is giving me a runtime error because no secret_key was set. Do you know where and how i should be setting this?

**Comment by bburns8** [comment]
blake@pop-os:~/PycharmProjects/portfolio_tracker-dev$ python3 main.py
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
20-01-2022:16:30:08 WARNING  [_internal.py:225]  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
20-01-2022:16:30:08 INFO     [_internal.py:225]  * Running on http://192.168.1.110:5000/ (Press CTRL+C to quit)
20-01-2022:16:30:17 ERROR    [app.py:1457] Exception on / [GET]
Traceback (most recent call last):
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/login_manager.py", line 165, in unauthorized
    flash(self.login_message, category=self.login_message_category)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/helpers.py", line 391, in flash
    session["_flashes"] = flashes
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
20-01-2022:16:30:17 INFO     [_internal.py:225] 192.168.1.110 - - [20/Jan/2022 16:30:17] "GET / HTTP/1.1" 500 -

**Comment by bburns8** [comment]
I'm guessing the issue is the SECRET_KEY in the config file has to be set to something, also the only other secret keys appear to be the binance api key and nomic api key

**Comment by gerardsyd** [comment]
Yep, two ways you can solve it. I recommend the second way given the repo is public on github (assuming you sync it).
1. You can directly insert the values in the config.py file. You will need to include values for SECRET_KEY (any long string), SQLALCHEMY_DATABASE_URI (this is set up to take a value or, if no value, it will create a file under data/app.db), CHROMEDRIVER_PATH and CHD_LOG_PATH (you won't need this as that is for some custom code and won't be used). 
2. Set up a .env file in your main folder. If  you are using a virtual environment like pipenv, it should read that env file when it loads and then the code should simply work (as-is). If you are not using a virtual environment, then you'll need to modify the code to read the dotenv file. This is fairly simple by installing dotenv (https://github.com/theskumar/python-dotenv#getting-started)

If you intend on tracking crypto (noting I need to fix a bunch of issues although it does work at a rudimentary level with AUD being the base converted currency), then you also need binance api keys and nomic api keys and then will need to include them in your .env file. These are free and you should be able to sign up and generate those keys. If not tracking crypto, I wouldn't bother.

**Comment by bburns8** [comment]
i am using a virtual environment, is the file i am supposed to be reading the alembic.env file? Sorry i am just a bit confused because that file doesn't have a secret key? Thank you for your patience with me I am still learning!

**Comment by bburns8** [comment]
I've also tried inserting a random long string into the secret key config file and that didn't work.. since i'm using a virtual env I made a .env file in the main directory but what exactly do I put inside of my .env file?

**Comment by bburns8** [comment]
thank you, i was able to get it working to the point where i could load the login/register page. however when i try to register an account I'm getting an error that says to check keyword arguments are appropriate for combination of components. I'm pretty sure I'm using all the correct validations for creating account. Any idea what this could be?

**Comment by bburns8** [comment]
Here's the full error received:


21-01-2022:13:56:20 ERROR    [app.py:1457] Exception on /register [POST]
Traceback (most recent call last):
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7faee54e1300 (otid=0x7faee551ed80) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/routes.py", line 66, in register
    if form.validate_on_submit():
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/wtforms/form.py", line 329, in validate
    return super().validate(extra)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/wtforms/form.py", line 146, in validate
    if not field.validate(self, extra):
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/wtforms/fields/core.py", line 242, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/wtforms/fields/core.py", line 262, in _run_validation_chain
    validator(form, self)
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/forms.py", line 24, in validate_username
    user = User.query.filter_by(username=username.data).first()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 128, in __call__
    return self.registry()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4027, in __call__
    return self.class_(**local_kw)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 633, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'pool_timeout' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
21-01-2022:13:56:20 INFO     [_internal.py:225] 192.168.1.110 - - [21/Jan/2022 13:56:20] "POST /register HTTP/1.1" 500 -

**Comment by bburns8** [comment]
the only problem I am having now is connecting with the database, do you have any steps on how I can create a sqlite database? or how did you set yours up?

**Comment by bburns8** [comment]
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.default_currency AS user_default_currency, user.last_accessed AS user_last_accessed 
FROM user 
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('blake-burns', 1, 0)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

**Comment by gerardsyd** [comment]
You're getting the error because the tables have not been created as yet. You need to create them in the initial set up.
I broadly followed Miguel Grinberg tutorial for the set up, database etc. See here: https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database

If you're just starting out, might be worthwhile going through his tutorial in the first instance and then applying it to this project.

**Comment by bburns8** [comment]
I was able to follow along and get the user table working, so I can register accounts. I can't figure out how to get the trades and stocks tables to work. Aren't they created with the models.py when you migrate? I seem to be getting an error

**Comment by bburns8** [comment]
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->user, expression 'Trade' failed to locate a name ('Trade'). If this is a class name, consider adding this relationship() to the <class 'app.models.User'> class after both dependent classes have been defined.

**Comment by gerardsyd** [comment]
do you have the full trace? I can't see what is calling this and when the error comes through. I haven't messed around with this in a while so my memory is a bit foggy around where / when the tables get created. 
Are your migrations being generated properly in alembic? You may need to check them manually to make sure it's working properly / as expected

**Comment by bburns8** [comment]
Traceback (most recent call last):
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 393, in _resolve_name
    rval = d[token]
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 746, in __missing__
    self[key] = val = self.creator(key)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 372, in _access_cls
    return self.fallback[key]
KeyError: 'Trade'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/utils.py", line 270, in decorated_view
    elif not current_user.is_authenticated:
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/werkzeug/local.py", line 432, in __get__
    obj = instance._get_current_object()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/werkzeug/local.py", line 554, in _get_current_object
    return self.__local()  # type: ignore
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/login_manager.py", line 318, in _load_user
    user = self._user_callback(user_id)
  File "/home/blake/PycharmProjects/portfolio_tracker-dev/app/models.py", line 31, in load_user
    return User.query.get(int(id))
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/base.py", line 436, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/base.py", line 415, in _inspect_mapped_class
    mapper._check_configure()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1874, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3423, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1891, in _post_configure_properties
    prop.init()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 227, in init
    self.do_init()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2131, in do_init
    self._process_dependent_arguments()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2226, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1095, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2093, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/orm/clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->user, expression 'Trade' failed to locate a name ('Trade'). If this is a class name, consider adding this relationship() to the <class 'app.models.User'> class after both dependent classes have been defined.

the migrations seem to be generated properly, one thing I see don't have is the versions repository that you have, could that be an issue?

**Comment by gerardsyd** [comment]
you wouldn't have the versions since you're starting fresh. The versions will only be relevant if you start changing the database model and then creating migration files. 

I downloaded the repo and tried it myself and it all seems to work fine. Here are the steps I took to make it work:
1. Created a virtual env and then ran pip install -r requirements.txt
2. In .env, I added:
FLASK_APP='pftracker.py'
FLASK_DEBUG=True
FLASK_ENV=development
SECRET_KEY='some_long_text_of_random_strings'
3. In config.py, I added/ changed:
    SQLALCHEMY_POOL_TIMEOUT = None
    SQLALCHEMY_POOL_SIZE = None
4. Deleted the migrations folder
5. Created a data folder
6. Inside virtual env terminal, I ran the following:
flask db init
flask db migrate -m 'create tables'
flask db upgrade

That should then let you run main.py and everything should be up and running. 

I did find two other issues when I was running it, fixes below:
1. yfinance has been updated. So in your virtual env terminal, run:
pip install yfinance -U
2. There's an issue with the portfolio class where a data file does not exist then it throws an error. In portfolio.py, replace the update_datafile function as follows (essentially just adding a check to see if the data file exists)
    def update_datafile(self, new_data: pd.DataFrame):
        # set index for new data
        new_data.set_index(['Ticker', 'Date'], inplace=True)

        # load saved data and set index, and combine if file exists
        if path.exists(self.filename):
            saved_data = pd.read_pickle(self.filename)
            saved_data.set_index(['Ticker', 'Date'], inplace=True)
            saved_data = saved_data.combine_first(new_data)
        else:
            saved_data = new_data

        # updates data for existing rows (e.g. when newer price data downloaded)
        saved_data.update(new_data)
        saved_data.reset_index(inplace=True)
        saved_data.to_pickle(self.filename)

If you are not running a virtual env, you can simply ignore my comments re: virtual env and just run those commands in your terminal.

Hope that helps.

**Comment by bburns8** [comment]
I followed your steps and appear to get the same error... once again when I run flask db migrate -m 'create tables' I am getting this traceback:

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [flask_migrate] Error: Can't locate revision identified by 'e1a1ccf64985'

I am also getting the same error when I run flask db upgrade

**Comment by bburns8** [comment]
Gerard, I can't thank you enough for the help. I was able to get it working after following your steps.

My last question would be how were you able to get the chart and graph on the home page to list all the specs of your added stocks such as (IRR, LastChange% Total Gain Etc.) When I go to add my stocks and save them and go to home the page is blank. I noticed on your website that is live it has a chart with all that information as well as a graph showing total gain vs current val which is cool.

 This is probably the best stock portfolio app that I have seen by the way amazing work!

**Comment by gerardsyd** [comment]
No worries. Did you press refresh process? That should generate the table. 
If you want to see an individual position, then click on the ticker (after the table refreshes) and it should take you to the chart.
Still a work in progress and I'm updating for FX etc etc. So please use with caution!

**Comment by bburns8** [comment]
When I refresh I get KeyError: 'Close'

Traceback (most recent call last):
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
    
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
    
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
KeyError: 'Close'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/blake/PycharmProjects/portfolio_tracker/app/routes.py", line 229, in pfactions
    return update_pf()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/blake/PycharmProjects/portfolio_tracker/app/routes.py", line 93, in update_pf
    df = pf.info_date(as_at_date=as_at_date,
  File "/home/blake/PycharmProjects/portfolio_tracker/app/portfolio.py", line 123, in info_date
    prices_df = self.curr_positions(
  File "/home/blake/PycharmProjects/portfolio_tracker/app/portfolio.py", line 406, in curr_positions
    prices_df['PrevPrice'] = prices_df.groupby(
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'Close'

**Comment by bburns8** [comment]
Shouldn't I be returning the home.jinja template instead of returning update_pf(), I notice when I search directly /stock/TSLA it will pull up the individual position of that stock but the graph doesn't have any lines, could I be missing something?

**Comment by gerardsyd** [comment]
update_pf() is a route under routes.py and has all the smarts for taking the information and converting into a dataframe which eventually sends the info to home.jinja and returns the rendered template. 
I think you're having an issue with updating the share prices. Are you using the most recent version of yfinance? I can get it working and it's pulling data fine so maybe yahoo was just down when you tried? Sometimes that is an issue? Otherwise I'm not sure why the prices are not working. What trades have you entered?

**Comment by bburns8** [comment]
I am using the most recent version of yfinance 0.1.69, The trades I entered were both buys of TSLA for 5 at 500 and MSFT for 50 at 300. I went ahead and deleted them and reran to see if the API was just down. It gave me a different error this time regarding no such file or directory 'data/pf_data.pkl'

**Comment by bburns8** [comment]
Traceback:
/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py:661: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  util.warn(
26-01-2022:13:47:36 DEBUG    [inotify_buffer.py:57] in-event <InotifyEvent: src_path=b'/home/blake/PycharmProjects/portfolio_tracker/data/app.db', wd=4, mask=IN_CLOSE_WRITE, cookie=0, name=app.db>
26-01-2022:13:47:36 DEBUG    [inotify_buffer.py:57] in-event <InotifyEvent: src_path=b'/home/blake/PycharmProjects/portfolio_tracker/data/app.db', wd=4, mask=IN_CLOSE_WRITE, cookie=0, name=app.db>
26-01-2022:13:47:36 DEBUG    [portfolio.py:70] -------  Check if DF has correct columns  -------
26-01-2022:13:47:36 DEBUG    [inotify_buffer.py:57] in-event <InotifyEvent: src_path=b'/home/blake/PycharmProjects/portfolio_tracker/data/app.db', wd=4, mask=IN_CLOSE_WRITE, cookie=0, name=app.db>
26-01-2022:13:47:36 DEBUG    [portfolio.py:73] Concatenating trades to trade_df
26-01-2022:13:47:36 DEBUG    [portfolio.py:119] Get historical and current positions and merge with info dataframe
26-01-2022:13:47:36 DEBUG    [data.py:31] -------  Ticker is TSLA  -------
26-01-2022:13:47:36 DEBUG    [data.py:31] -------  Ticker is MSFT  -------
26-01-2022:13:47:36 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): query2.finance.yahoo.com:443
26-01-2022:13:47:36 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): query2.finance.yahoo.com:443
26-01-2022:13:47:36 DEBUG    [connectionpool.py:452] https://query2.finance.yahoo.com:443 "GET /v8/finance/chart/TSLA?period1=1642406400&period2=1643204856&interval=1d&includePrePost=False&events=div%2Csplits HTTP/1.1" 200 1423
26-01-2022:13:47:36 DEBUG    [connectionpool.py:452] https://query2.finance.yahoo.com:443 "GET /v8/finance/chart/MSFT?period1=1642406400&period2=1643204856&interval=1d&includePrePost=False&events=div%2Csplits HTTP/1.1" 200 1491
26-01-2022:13:47:36 DEBUG    [data.py:47] Data downloaded for TSLA: Start: 2022-01-17 | End: 2022-01-26
26-01-2022:13:47:36 DEBUG    [data.py:47] Data downloaded for MSFT: Start: 2022-01-17 | End: 2022-01-26
26-01-2022:13:47:36 DEBUG    [data.py:73] Obtained data, concatenating
26-01-2022:13:47:36 INFO     [portfolio.py:403] update prices took 0:00:00.270212 to run
/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/pandas/core/groupby/groupby.py:2723: FutureWarning: Passing <class 'int'> to shift is deprecated and will raise in a future version, pass Timestamp instead.
  return self.apply(lambda x: x.shift(periods, freq, axis, fill_value))
26-01-2022:13:47:36 INFO     [portfolio.py:412] last change took 0:00:00.016016 to run
26-01-2022:13:47:36 INFO     [_internal.py:113] 127.0.0.1 - - [26/Jan/2022 13:47:36] "POST /pfactions HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/blake/PycharmProjects/portfolio_tracker/app/routes.py", line 229, in pfactions
    return update_pf()
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/blake/PycharmProjects/portfolio_tracker/app/routes.py", line 93, in update_pf
    df = pf.info_date(as_at_date=as_at_date,
  File "/home/blake/PycharmProjects/portfolio_tracker/app/portfolio.py", line 125, in info_date
    self.update_datafile(prices_df.copy(deep=True))
  File "/home/blake/PycharmProjects/portfolio_tracker/app/portfolio.py", line 580, in update_datafile
    saved_data = pd.read_pickle(self.filename)
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/pandas/io/pickle.py", line 185, in read_pickle
    with get_handle(
  File "/home/blake/PycharmProjects/venv/lib/python3.9/site-packages/pandas/io/common.py", line 651, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/pf_data.pkl'

**Comment by gerardsyd** [comment]
Hi, per my previous comment, update the portfolio file as per below... Also make sure you have a data folder (just create one in the main folder. 

There's an issue with the portfolio class where a data file does not exist then it throws an error. In portfolio.py, replace the update_datafile function as follows (essentially just adding a check to see if the data file exists)
def update_datafile(self, new_data: pd.DataFrame):
# set index for new data
new_data.set_index(['Ticker', 'Date'], inplace=True)

 # load saved data and set index, and combine if file exists
 if path.exists(self.filename):
     saved_data = pd.read_pickle(self.filename)
     saved_data.set_index(['Ticker', 'Date'], inplace=True)
     saved_data = saved_data.combine_first(new_data)
 else:
     saved_data = new_data

 # updates data for existing rows (e.g. when newer price data downloaded)
 saved_data.update(new_data)
 saved_data.reset_index(inplace=True)
 saved_data.to_pickle(self.filename)

**Comment by bburns8** [comment]
Apologies, I thought I had already done that! Thanks again Gerard I'll be sure to let you know if I find any bugs that you may want to know about!!

Cheers!
